"""Tracks table.

Revision ID: b9d519bc4a6d
Revises:
Create Date: 2021-10-10 19:31:51.174873

"""
import sqlalchemy as sa
from alembic import context, op

# revision identifiers, used by Alembic.
revision = "b9d519bc4a6d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    schema_upgrade()
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_upgrade()


def downgrade() -> None:
    if context.get_x_argument(as_dictionary=True).get("data"):
        data_downgrade()
    schema_downgrade()


def schema_upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("song_time", sa.DateTime(), nullable=False),
        sa.Column("song_artist", sa.String(length=128), nullable=False),
        sa.Column("song_title", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def schema_downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracks")
    # ### end Alembic commands ###


def data_upgrade() -> None:
    pass


def data_downgrade() -> None:
    pass
